### PR TITLE
Downgrade to 0.15.2 for py39 build

### PR DESCRIPTION
**Pull request by asford**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by asford** [comment]
@ocefpaf
@nehaljwani
@pmlandwehr

I'm not exactly how to handle this, but cutting a down-graded build for python 3.9 is likely the easiest way of unblocking the py39 update for awscli. See https://github.com/conda-forge/awscli-feedstock/pull/696 for references and details.

It it possible to maintain an additional non-`master` branch that will deploy packages to `conda-forge`? Alternatively, we could just merge-to-build then immediately revert this PR.

**Comment by ocefpaf** [comment]
@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
I created a branch, removed an unnecessary comment, and requested a re-render. But some extra work is required on macOS to get this passing on all platforms.

**Comment by ocefpaf** [comment]
Re-rendering solve it!

**Comment by asford** [comment]
@ocefpaf Thanks! To clarify for my understanding, any branch in the `conda-forge` feedstock repo will be built and deployed to the channel? We can use the `v0.15.x` for maintenance if required?

**Comment by ocefpaf** [comment]
> @ocefpaf Thanks! To clarify for my understanding, any branch in the `conda-forge` feedstock repo will be built and deployed to the channel? We can use the `v0.15.x` for maintenance if required?

Yep. That is the idea. We try to reduce those to just a few essential versions though, to avoid a proliferation of multiple versions we need to support.

**Pull request merged**
