### PR TITLE
Build 0.15.x for Pypy3.8/3.9

### LINKED ISSUE #42: Could an older version of this feedstock be built for pypy3.8,pypy3.9
### Comment:

In PR #40 the feedstock was built for pypy3.8/3.9 at version 1.18.1. It turns out the awscli package pins `docutils >=0.10,<0.17`, which then fails to build since only 1.18.1 and later is available. Would it be acceptable to build an older version for pypy3.8/3.9 that satisfies that requirement? See https://github.com/conda-forge/awscli-feedstock/pull/1113#issuecomment-1196315258 for a request to loosen the pin instead, I am not sure what is easier.

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #42

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
Uhh, what? Nothing succeeded. Something about `error: metadata-generation-failed` ?

**Comment by mattip** [comment]
@conda-forge-admin please restart ci

**Comment by mattip** [comment]
The problem was that `setuptools.distutils` no longer has `build_py_2to3`, so setup.py fails. The solution is to pin setuptools to the last available version before [v58.0.0](https://setuptools.pypa.io/en/latest/history.html#v58-0-0), which is 57.4 on conda-forge.

**Comment by mattip** [comment]
Now the resolver cannot find setuptools 57.4 for cpython10, pypy. What a tangled web we weave ...

**Comment by tkelman** [comment]
Bit complicated to install setuptools from source, but looks like it did the job here. Thanks so much for your work on this!

**Comment by mattip** [comment]
CI is passing. I needed to install from source since for some reason `pip install setuptools==57.4.0` could not find the pypi.org wheels.

**Comment by tkelman** [comment]
@ocefpaf opinions here? looks like the other maintainer's been offline for most of the last week

**Comment by ocefpaf** [comment]
> @ocefpaf opinions here? looks like the other maintainer's been offline for most of the last week

That is why we usually wait at least 2-weeks for extra pings :wink: 
Also, this PR happened over the weekend! Despite of the appearances we are humans!

**Comment by mattip** [comment]
Thanks!

**Comment by ocefpaf** [comment]
> Thanks!

Thank you for taking care of the pypy stack!

**Pull request merged**
