### PR TITLE
Remove custom setuptools

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #43 to remove the new version of setuptools after building the package, to avoid packaging this setuptools into the package.
See https://github.com/conda-forge/artifact-validation/issues/897#issuecomment-1206485235

### CODE REVIEW

**Comment by ocefpaf** [comment]
@mattip let me see if I can add a fresh build of setuptools 57.4.0 instead. Hold on...

**Comment by mattip** [comment]
windows 3.7 cpython is failing to build the git-downloaded version of setuptools, [claiming](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=546545&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=363) 
`ModuleNotFoundError: No module named '_distutils_hack'`

**Comment by ocefpaf** [comment]
I believe this is good to go now. Let's give it a try. Thanks @mattip!

**Comment by mattip** [comment]
Thanks, sorry for the additional work.

**Pull request merged**
